tenderwebsite-main/tenderwebsite-main/tender/accounts/urls.py
from django.urls import path

from . import views

app_name = 'accounts'

urlpatterns = [
    path('', views.register, name='register'),
    path('user_login/', views.user_login, name='user_login'),
]

tenderwebsite-main/tenderwebsite-main/tender/eoi/urls.py
from django.urls import path
from . import views

app_name = 'eoi'


urlpatterns = [
    path('', views.all, name='all'),
    path('<slug>', views.single, name='single'),
]

tenderwebsite-main/tenderwebsite-main/tender/profiles/urls.py
from django.conf import settings
from django.conf.urls.static import static

from .views import ProfileDetailView, ProfileUpdateView
from django.conf.urls import url

app_name = 'profiles'

urlpatterns = [
    url(r'^(?P<username>[\w-]+)/$', ProfileDetailView.as_view(), name='detail'),
    url(r'^update/(?P<pk>\d+)/$', ProfileUpdateView.as_view(), name='update')
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tenderwebsite-main/tenderwebsite-main/tender/tender/urls.py
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('accounts.urls')),
    path('logout/', views.user_logout, name='logout'),

    path('', include('tenderapp.urls')),
    path('tender/', include('tenderonly.urls')),
    path('auction/', include('auction.urls')),
    path('eoi/', include('eoi.urls')),
    path('intent2award/', include('intent2awards.urls')),
    path('others/', include('others.urls')),
    path('proposal/', include('proposal.urls')),
    path('quotation/', include('quotation.urls')),
    path('standing-list/', include('standinglist.urls')),
    path('advertising/', include('advertise.urls'), name='advertising'),

    path('s/', views.search, name='search'),
    path('u/', include('profiles.urls', namespace='profiles')),

    path('aboutus/', views.AboutUs.as_view(), name='aboutus'),
    path('contact-us/', views.ContactUs.as_view(), name='contactus'),
    path('pricing/', views.Pricing.as_view(), name='pricing'),
    path('faq/', views.Faq.as_view(), name='faq'),
    path('team/', views.Team.as_view(), name='team'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

tenderwebsite-main/tenderwebsite-main/tender/accounts/models.py
from django.db import models

from django.contrib.auth.models import User
from django.urls import reverse
from memberships.models import Membership


def upload_location(instance, filename):
    return "%s/%s" % (instance.user, filename)


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    company_name = models.CharField(max_length=30, blank=True, null=True)
    contact_person_name = models.CharField(max_length=30, blank=True, null=True)
    address = models.CharField(max_length=30, blank=True, null=True)
    mobile_number = models.CharField(max_length=13, null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    allowed_memberships = models.ManyToManyField(Membership)

    def get_absolute_url(self):
        return reverse("profiles:detail", kwargs={'username': self.user.username})

    def __str__(self):
        return self.user.username

tenderwebsite-main/tenderwebsite-main/tender/profiles/models.py
from django.db import models

# Create your models here.

tenderwebsite-main/tenderwebsite-main/tender/accounts/forms.py
from django.contrib.auth.models import User
from django import forms

from accounts.models import Profile


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'email', 'password')


class ProfileForm(forms.ModelForm):

    class Meta:
        model = Profile
        fields = ('company_name', 'contact_person_name', 'address', 'mobile_number')

tenderwebsite-main/tenderwebsite-main/tender/accounts/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render, redirect
from django.urls import reverse

from accounts.forms import UserForm, ProfileForm
# Create your views here.


def register(request):
    registered = False

    if request.method == "POST":
        user_form = UserForm(data=request.POST)
        profile_form = ProfileForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']

            profile.save()
            registered = True
            return redirect('tender:all')

        else:
            print(user_form.errors, profile_form.errors)


    else:
        user_form = UserForm()
        profile_form = ProfileForm()

    return render(request, 'registration.html', {'user_form':user_form,
                                                          'profile_form':profile_form,
                                                          'registered':registered})


def user_login(request):
    if request.method == "POST":
        username = request.POST.get("username")
        password = request.POST.get("password")

        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('tender:all'))

            else:
                messages.error(request, "Invalid username or password.")
                return HttpResponse("Account not active")

        else:
            messages.error(request, "Invalid username or password.")
            return redirect('tender:all')

    else:
        return render(request, 'accounts/login.html')

tenderwebsite-main/tenderwebsite-main/tender/profiles/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import DetailView, UpdateView
from django.http import Http404
from accounts.models import Profile
from memberships.models import Membership, UserMembership


User = get_user_model()


class ProfileDetailView(LoginRequiredMixin, DetailView):

    template_name = 'profiles/user.html'

    def get_object(self):
        username = self.kwargs.get("username")
        if username is None:
            raise Http404
        return get_object_or_404(User, username__iexact=username, is_active=True)


class ProfileUpdateView(LoginRequiredMixin, UpdateView):

    fields = ('address', 'mobile_number')
    model = Profile

tenderwebsite-main/tenderwebsite-main/tender/accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% block content %}

 <div class="jumbotron jumbotron-fluid">
 {% if messages %}
<ul>
   {% for message in messages %}
	   <li>{{ message }}</li>
   {% endfor %}
</ul>
{% endif %}
    <h1>Please Login</h1>
        <form action="{% url 'accounts:user_login' %}" method="POST">
            {% csrf_token %}
            <label for="username">Username:</label>
            <input type="text" name="username" placeholder="Username">

            <label for="password">Password:</label>
            <input type="password" name="password">
            <input type="submit" value="Login">
        </form>
        Don't have an account? <a href="{% url 'accounts:register' %}" target="blank"><strong>register here</strong></a>!
        </div>

{% endblock %}

tenderwebsite-main/tenderwebsite-main/tender/accounts/templates/accounts/profile_form.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content%}

<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {% bootstrap_form form %}
    <input class="btn btn-warning" type="submit" value="Submit">
</form>
{% endblock %}

tenderwebsite-main/tenderwebsite-main/tender/accounts/templates/accounts/registration.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}
    <div class="jumbotron">
        {% if registered %}
            <h1>Thanks for registration!</h1>
        {% else %}
        <h1>Sign Up</h1>
        <h4>you are one step away.</h4>
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="form-row">
                <div class="form-group col-md-6 ">
                 {% bootstrap_form user_form %}
                </div>
                <div class="form-group col-md-6">
                  {% bootstrap_form profile_form %}
                <input type="submit" value="Register" class="btn btn-success">
                </div>
             </div>



        </form>
        {% endif %}

    </div>

{% endblock %}