tenderwebsite-main/tenderwebsite-main/tender/auction/urls.py
from django.urls import path
from . import views

app_name = 'auction'


urlpatterns = [
    path('', views.all, name='all'),
    path('<slug>', views.single, name='single'),
]

tenderwebsite-main/tenderwebsite-main/tender/eoi/urls.py
from django.urls import path
from . import views

app_name = 'eoi'


urlpatterns = [
    path('', views.all, name='all'),
    path('<slug>', views.single, name='single'),
]

tenderwebsite-main/tenderwebsite-main/tender/others/urls.py
from django.urls import path
from . import views

app_name = 'others'


urlpatterns = [
    path('', views.all, name='all'),
    path('<slug>', views.single, name='single'),
]

tenderwebsite-main/tenderwebsite-main/tender/proposal/urls.py
from django.urls import path
from . import views

app_name = 'proposal'


urlpatterns = [
    path('', views.all, name='all'),
    path('<slug>', views.single, name='single'),
]

tenderwebsite-main/tenderwebsite-main/tender/quotation/urls.py
from django.urls import path
from . import views

app_name = 'quotation'


urlpatterns = [
    path('', views.all, name='all'),
    path('<slug>', views.single, name='single'),
]

tenderwebsite-main/tenderwebsite-main/tender/tender/urls.py
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('accounts.urls')),
    path('logout/', views.user_logout, name='logout'),

    path('', include('tenderapp.urls')),
    path('tender/', include('tenderonly.urls')),
    path('auction/', include('auction.urls')),
    path('eoi/', include('eoi.urls')),
    path('intent2award/', include('intent2awards.urls')),
    path('others/', include('others.urls')),
    path('proposal/', include('proposal.urls')),
    path('quotation/', include('quotation.urls')),
    path('standing-list/', include('standinglist.urls')),
    path('advertising/', include('advertise.urls'), name='advertising'),

    path('s/', views.search, name='search'),
    path('u/', include('profiles.urls', namespace='profiles')),

    path('aboutus/', views.AboutUs.as_view(), name='aboutus'),
    path('contact-us/', views.ContactUs.as_view(), name='contactus'),
    path('pricing/', views.Pricing.as_view(), name='pricing'),
    path('faq/', views.Faq.as_view(), name='faq'),
    path('team/', views.Team.as_view(), name='team'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

tenderwebsite-main/tenderwebsite-main/tender/tenderapp/urls.py
from django.urls import path
from . import views

app_name = 'tender'


urlpatterns = [
    path('', views.all, name='all'),
    path('<slug>', views.single, name='single'),
    path('package-form/', views.pricing_clients, name='pricing_form'),
]

tenderwebsite-main/tenderwebsite-main/tender/tenderonly/urls.py
from django.urls import path
from . import views

app_name = 'tenderonly'


urlpatterns = [
    path('', views.all, name='all'),
    path('<slug>', views.single, name='single'),
]

tenderwebsite-main/tenderwebsite-main/tender/auction/models.py
from django.db import models
from django.urls import reverse
from memberships.models import Membership

def upload_location(instance, filename):
    return "%s/%s" % (instance.title, filename)


def document_upload_location(instance, filename):
    return "%s/%s"%(instance.syllabus, filename)


class Auction(models.Model):
    title = models.CharField(max_length=255, unique=True)
    org_name = models.CharField(max_length=50, blank=True, null=True)
    org_address = models.CharField(max_length=50, blank=True, null=True)
    service = models.CharField(max_length=50, blank=True, null=True)
    tender_description = models.TextField()
    syllabus = models.FileField(upload_to=document_upload_location, blank=True, null=True)
    published_on = models.CharField(max_length=55, unique=True)
    published_date = models.DateTimeField()
    last_date = models.DateTimeField()
    picture = models.ImageField(upload_to=upload_location, blank=True, null=True)
    slug = models.SlugField(allow_unicode=True, unique=True, blank=True, null=True)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    allowed_memberships = models.ManyToManyField(Membership)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("tenderapp:all", kwargs={'slug': self.slug})

tenderwebsite-main/tenderwebsite-main/tender/eoi/models.py
from django.db import models
from django.urls import reverse


def upload_location(instance, filename):
    return "%s/%s" % (instance.title, filename)


def document_upload_location(instance, filename):
    return "%s/%s"%(instance.syllabus, filename)


class Eoi(models.Model):
    title = models.CharField(max_length=255, unique=True)
    org_name = models.CharField(max_length=50, blank=True, null=True)
    org_address = models.CharField(max_length=50, blank=True, null=True)
    service = models.CharField(max_length=50, blank=True, null=True)
    tender_description = models.TextField()
    syllabus = models.FileField(upload_to=document_upload_location, blank=True, null=True)
    published_on = models.CharField(max_length=55, unique=True)
    published_date = models.DateTimeField()
    last_date = models.DateTimeField()
    picture = models.ImageField(upload_to=upload_location, blank=True, null=True)
    slug = models.SlugField(allow_unicode=True, unique=True, blank=True, null=True)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("eoi:all", kwargs={'slug': self.slug})

tenderwebsite-main/tenderwebsite-main/tender/tenderapp/forms.py
from django import forms
from .models import PricingClientInfo


class PricingClientForm(forms.ModelForm):
    class Meta:
        model = PricingClientInfo
        fields = "__all__"

tenderwebsite-main/tenderwebsite-main/tender/auction/views.py
from django.http import Http404
from django.shortcuts import render
from .models import Auction
from memberships.models import Membership, UserMembership


def all(request):
    auction = Auction.objects.order_by('-published_date')
    context = {'auction': auction}
    template = 'auction/all.html'
    return render(request, template, context)


def single(request, slug):
    try:
        auction = Auction.objects.get(slug=slug)
        user_membership = UserMembership.objects.filter(user=request.user).first()
        user_membership_type = user_membership.membership.membership_type
        context = {'tender': auction, 'user_membership_type':user_membership_type}
        template = 'auction/single.html'
        return render(request, template, context)

    except:
        return render(request, 'loginrequired.html')

tenderwebsite-main/tenderwebsite-main/tender/eoi/views.py
from django.http import Http404
from django.shortcuts import render
from .models import Eoi
from memberships.models import Membership, UserMembership


def all(request):
    eoi = Eoi.objects.order_by('-published_date')
    context = {'eoi': eoi}
    template = 'eoi/all.html'
    return render(request, template, context)


def single(request, slug):
    try:
        auction = Eoi.objects.get(slug=slug)
        user_membership = UserMembership.objects.filter(user=request.user).first()
        user_membership_type = user_membership.membership.membership_type

        context = {'tender': auction, 'user_membership_type':user_membership_type}
        template = 'eoi/single.html'
        return render(request, template, context)

    except:
        return render(request, 'loginrequired.html')

tenderwebsite-main/tenderwebsite-main/tender/intent2awards/views.py
from django.http import Http404
from django.shortcuts import render
from .models import Intents2Awards
from memberships.models import Membership, UserMembership


def all(request):
    auction = Intents2Awards.objects.order_by('-published_date')
    context = {'auction': auction}
    template = 'intent2awards/all.html'
    return render(request, template, context)


def single(request, slug):
    try:
        auction = Intents2Awards.objects.get(slug=slug)
        user_membership = UserMembership.objects.filter(user=request.user).first()
        user_membership_type = user_membership.membership.membership_type

        context = {'tender': auction, 'user_membership_type':user_membership_type}
        template = 'intent2awards/single.html'
        return render(request, template, context)

    except:
        return render(request, 'loginrequired.html')

tenderwebsite-main/tenderwebsite-main/tender/others/views.py
from django.http import Http404
from django.shortcuts import render
from .models import Others
from memberships.models import Membership, UserMembership


def all(request):
    auction = Others.objects.order_by('-published_date')
    context = {'auction': auction}
    template = 'others/all.html'
    return render(request, template, context)


def single(request, slug):
    try:
        auction = Others.objects.get(slug=slug)
        user_membership = UserMembership.objects.filter(user=request.user).first()
        user_membership_type = user_membership.membership.membership_type

        context = {'tender': auction, 'user_membership_type':user_membership_type}
        template = 'others/single.html'
        return render(request, template, context)
    except:
        return render(request, 'loginrequired.html')

tenderwebsite-main/tenderwebsite-main/tender/proposal/views.py
from django.http import Http404
from django.shortcuts import render
from .models import Proposal
from memberships.models import Membership, UserMembership


def all(request):
    auction = Proposal.objects.order_by('-published_date')
    context = {'auction': auction}
    template = 'proposal/all.html'
    return render(request, template, context)


def single(request, slug):
    try:
        auction = Proposal.objects.get(slug=slug)
        user_membership = UserMembership.objects.filter(user=request.user).first()
        user_membership_type = user_membership.membership.membership_type
    
        context = {'tender': auction, 'user_membership_type':user_membership_type}
        template = 'proposal/single.html'
        return render(request, template, context)

    except:
        return render(request, 'loginrequired.html')

tenderwebsite-main/tenderwebsite-main/tender/quotation/views.py
from django.http import Http404
from django.shortcuts import render
from .models import Quotation
from memberships.models import Membership, UserMembership


def all(request):
    auction = Quotation.objects.order_by('-published_date')
    context = {'auction': auction}
    template = 'quotation/all.html'
    return render(request, template, context)


def single(request, slug):
    try:
        auction = Quotation.objects.get(slug=slug)
        user_membership = UserMembership.objects.filter(user=request.user).first()
        user_membership_type = user_membership.membership.membership_type

        context = {'tender': auction, 'user_membership_type':user_membership_type}
        template = 'quotation/single.html'
        return render(request, template, context)

    except:
        return render(request, 'loginrequired.html')

tenderwebsite-main/tenderwebsite-main/tender/standinglist/views.py
from django.http import Http404
from django.shortcuts import render
from .models import StandingList
from memberships.models import Membership, UserMembership


def all(request):
    auction = StandingList.objects.order_by('-published_date')
    context = {'auction': auction}
    template = 'standinglist/all.html'
    return render(request, template, context)


def single(request, slug):
    try:
        auction = StandingList.objects.get(slug=slug)
        user_membership = UserMembership.objects.filter(user=request.user).first()
        user_membership_type = user_membership.membership.membership_type

        context = {'tender': auction, 'user_membership_type':user_membership_type}
        template = 'standinglist/single.html'
        return render(request, template, context)

    except:
        return render(request, 'loginrequired.html')

tenderwebsite-main/tenderwebsite-main/tender/tender/views.py
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views.generic import View, TemplateView

from django.shortcuts import render
from tenderapp.models import Tender
from auction.models import Auction
from eoi.models import Eoi
from intent2awards.models import Intents2Awards
from others.models import Others
from proposal.models import Proposal
from quotation.models import Quotation
from standinglist.models import StandingList
from django.db.models import Q

class AboutUs(TemplateView):
    template_name = 'aboutus.html'


class ContactUs(TemplateView):
    template_name = 'contactus.html'


class Pricing(TemplateView):
    template_name = 'pricing.html'


class Faq(TemplateView):
    template_name = 'faq.html'


class Team(TemplateView):
    template_name = 'team.html'


def search(request):
    try:
        q = request.GET.get('q')
    except:
        q = None
    if q:
        tender = Tender.objects.filter(
            Q(title__icontains=q, ) |
            Q(service__icontains=q) |
            Q(org_address__icontains=q, org_address__iexact=q)
        )
        auction = Auction.objects.filter(title__icontains=q)
        eoi = Eoi.objects.filter(title__icontains=q)
        intent2awards = Intents2Awards.objects.filter(title__icontains=q)
        others = Others.objects.filter(title__icontains=q)
        proposal = Proposal.objects.filter(title__icontains=q)
        quotation = Quotation.objects.filter(title__icontains=q)
        standinglist = StandingList.objects.filter(title__icontains=q)
        context = {'query': q, 'tender': tender, 'auction': auction, 'eoi': eoi, 'intent2awards': intent2awards, 'others': others,
                   'proposal': proposal, 'quotation': quotation, 'standinglist': standinglist}

        template = 'result.html'
    else:
        template = 'tenderapp/all.html'
        context = {}
    return render(request, template, context)



@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('tender:all'))

tenderwebsite-main/tenderwebsite-main/tender/tenderapp/views.py
from django.http import Http404
from django.shortcuts import render
from .models import Tender
from auction.models import Auction
from eoi.models import Eoi
from intent2awards.models import Intents2Awards
from others.models import Others
from proposal.models import Proposal
from quotation.models import Quotation
from standinglist.models import StandingList
from advertise.models import Advertising
from .forms import PricingClientForm
from django.contrib.auth.decorators import login_required
from memberships.models import Membership, UserMembership


def all(request):
    tender = Tender.objects.order_by('-created_at')[:4]
    auction = Auction.objects.order_by('-created_at')[:4]
    eoi = Eoi.objects.order_by('-created_at')[:4]
    intent2awards = Intents2Awards.objects.order_by('-created_at')[:]
    others = Others.objects.order_by('-created_at')[:4]
    proposal = Proposal.objects.order_by('-created_at')[:4]
    quotation = Quotation.objects.order_by('-created_at')[:4]
    standinglist = StandingList.objects.order_by('-created_at')[:4]
    advertise = Advertising.objects.order_by('-timestamp')[:4]
    context = {'tender': tender, 'auction': auction, 'eoi': eoi, 'intent2awards': intent2awards, 'others': others, 'proposal': proposal, 'quotation': quotation, 'standinglist': standinglist, 'advertise': advertise}
    template = 'tenderapp/all.html'
    return render(request, template, context)


def single(request, slug):
    try:
        tender = Tender.objects.get(slug=slug)
        advertise = Advertising.objects.order_by('-timestamp')[:3]
        user_membership = UserMembership.objects.filter(user=request.user).first()
        user_membership_type = user_membership.membership.membership_type
        context = {'tender': tender, 'advertise': advertise, 'user_membership_type':user_membership_type}
        template = 'tenderapp/single.html'
        return render(request, template, context)

    except:
        return render(request, 'loginrequired.html')


def pricing_clients(request):
    form = PricingClientForm()

    if request.method == "POST":
        form = PricingClientForm(request.POST)

        if form.is_valid():
            form.save(commit=True)
            return render(request, 'thankyou.html')

        else:
            print("Error form INVALID!")

    return render(request, 'tenderapp/pricing_clients.html', {'form': form})

tenderwebsite-main/tenderwebsite-main/tender/tenderapp/templates/tenderapp/snippets/auction.html
<section id="tender">
    <div class="alert alert-success" role="alert">
        <h2> <a href="{% url 'auction:all' %}">Auction </a></h2>
    </div>

                <div class="row">
                {% for t in auction %}
                <div class="col-sm-6 col-md-6 col-lg-3 col-xl-3">
                    <div class="card h-100">
                        <div class="card">
                            {% if t.picture %}
                            <a href="{% url 'auction:single' t.slug %}">
                                <img src="{{t.picture.url}}" class="card-img-top" alt="...">
                            </a>
                            {% endif %}
                            <div class="card-body">
                                <h5 class="card-title">{{t.title}}</h5>
                                <p class="card-text"><i class="fa fa-map-marker"></i>{{t.org_name}}</p>
                                <p class="card-text"><i class="fa fa-briefcase" aria-hidden="true"></i>{{t.service}}</p>
                            </div>
                            <ul class="list-group list-group-flush">
                                <li class="list-group-item">Published Date: {{t.published_date}}</li>
                                <li class="list-group-item">Last Date: {{t.last_date}}</li>
                            </ul>
                            <a href="{% url 'auction:single' t.slug %}" class="btn btn-primary">Visit Tender/Notice</a>
                        </div>
                    </div>
                </div>
                {% endfor %}

            </div>


</section>

tenderwebsite-main/tenderwebsite-main/tender/tenderapp/templates/tenderapp/snippets/eoi.html
<section id="tender">
    <div class="alert alert-success" role="alert">
        <h2> <a href="{% url 'eoi:all' %}">EOI - आशयपत्र माग </a></h2>
    </div>
<br>
     <div class="card-group">
                {% for t in eoi %}
                <div class="col-sm-6 col-md-6 col-lg-3 col-xl-3">
                    <div class="card h-100">
                        <div class="card">
                            {% if t.picture %}
                            <a href="{% url 'eoi:single' t.slug %}">
                                <img src="{{t.picture.url}}" class="card-img-top" alt="...">
                            </a>
                            {% endif %}
                            <div class="card-body">
                                <h5 class="card-title">{{t.title}}</h5>
                                <p class="card-text"><i class="fa fa-map-marker"></i>{{t.org_name}}</p>
                                <p class="card-text"><i class="fa fa-briefcase" aria-hidden="true"></i>{{t.service}}</p>
                            <p class="card-text"><i class="fa fa-newspaper-o" aria-hidden="true"></i>{{t.published_on}}</p>
                            </div>
                            <ul class="list-group list-group-flush">
                                <li class="list-group-item">Published Date: {{t.published_date|date}}</li>
                                <li class="list-group-item">Last Date: {{t.last_date|date}}</li>
                            </ul>
                            <a href="{% url 'eoi:single' t.slug %}" class="btn btn-primary">Visit Tender/Notice</a>
                        </div>
                    </div>
                </div>
                {% endfor %}

            </div>

</section>

tenderwebsite-main/tenderwebsite-main/tender/tenderapp/templates/tenderapp/snippets/horizontal-sidebar.html
<hr>
<div class="horizontal-sidebar">

    <a href="{% url 'tenderonly:all' %}">
        <button type="button" class="btn btn-primary">Tender - बोलपत्र</button>
    </a>
    <a href="{% url 'quotation:all' %}">
        <button type="button" class="btn btn-primary">Quotation - दरभाउपत्र</button>
    </a>
    <a href="{% url 'auction:all' %}">
        <button type="button" class="btn btn-primary">Auction - लिलामी</button>
    </a>
    <a href="{% url 'proposal:all' %}">
        <button type="button" class="btn btn-primary">Proposal - प्रस्तावना</button>
    </a>
    <a href="{% url 'eoi:all' %}">
        <button type="button" class="btn btn-primary">EOI - आशयपत्र माग</button>
    </a>
    <a href="{% url 'standinglist:all' %}">
        <button type="button" class="btn btn-primary">Standing List - सूचीदर्ता</button>
    </a>
    <a href="{% url 'intent2awards:all' %}">
        <button type="button" class="btn btn-primary">Intent to Award - आशयपत्र जारी</button>
    </a>
</div>

tenderwebsite-main/tenderwebsite-main/tender/tenderapp/templates/tenderapp/snippets/others.html
<section id="tender">
    <div class="alert alert-success" role="alert">
        <h2> <a href="{% url 'others:all' %}">Others</a> </h2>
    </div>
<br>
     <div class="card-group">

                {% for t in others %}
                <div class="col-sm-6 col-md-6 col-lg-3 col-xl-3">
                    <div class="card h-100">
                        <div class="card">
                            {% if t.picture %}
                            <a href="{% url 'others:single' t.slug %}">
                                <img src="{{t.picture.url}}" class="card-img-top" alt="...">
                            </a>
                            {% endif %}
                            <div class="card-body">
                                <h5 class="card-title">{{t.title}}</h5>
                                <p class="card-text"><i class="fa fa-map-marker"></i>{{t.org_name}}</p>
                                <p class="card-text"><i class="fa fa-briefcase" aria-hidden="true"></i>{{t.service}}</p>
                            <p class="card-text"><i class="fa fa-newspaper-o" aria-hidden="true"></i>{{t.published_on}}</p>
                            </div>
                            <ul class="list-group list-group-flush">
                                <li class="list-group-item">Published Date: {{t.published_date|date}}</li>
                                <li class="list-group-item">Last Date: {{t.last_date|date}}</li>
                            </ul>
                            <a href="{% url 'others:single' t.slug %}" class="btn btn-primary">Visit Tender/Notice</a>
                        </div>
                    </div>
                </div>
                {% endfor %}

            </div>
</section>

tenderwebsite-main/tenderwebsite-main/tender/tenderapp/templates/tenderapp/snippets/proposal.html
<section id="tender">
    <div class="alert alert-success" role="alert">
        <h2><a href="{% url 'proposal:all' %}"> Proposal - प्रस्तावना</a> </h2>
    </div>
<br>
         <div class="card-group">

                {% for t in proposal %}
              <div class="col-sm-6 col-md-6 col-lg-3 col-xl-3">
                    <div class="card h-100">
                        <div class="card">
                            {% if t.picture %}
                            <a href="{% url 'proposal:single' t.slug %}">
                                <img src="{{t.picture.url}}" class="card-img-top" alt="...">
                            </a>
                            {% endif %}
                            <div class="card-body">
                                <h5 class="card-title">{{t.title}}</h5>
                                <p class="card-text"><i class="fa fa-map-marker"></i>{{t.org_name}}</p>
                                <p class="card-text"><i class="fa fa-briefcase" aria-hidden="true"></i>{{t.service}}</p>
                            <p class="card-text"><i class="fa fa-newspaper-o" aria-hidden="true"></i>{{t.published_on}}</p>
                            </div>
                            <ul class="list-group list-group-flush">
                                <li class="list-group-item">Published Date: {{t.published_date|date}}</li>
                                <li class="list-group-item">Last Date: {{t.last_date|date}}</li>
                            </ul>
                            <a href="{% url 'proposal:single' t.slug %}" class="btn btn-primary">Visit Tender/Notice</a>
                        </div>
                    </div>
                </div>
                {% endfor %}

            </div>

</section>

tenderwebsite-main/tenderwebsite-main/tender/tenderapp/templates/tenderapp/snippets/quotation.html
<section id="tender">
    <div class="alert alert-success" role="alert">
        <h2><a href="{% url 'quotation:all' %}"> Quotation - दरभाउपत्र</a></h2>
    </div>
<br>
         <div class="card-group">

                {% for t in quotation %}
                <div class="col-sm-6 col-md-6 col-lg-3 col-xl-3">
                    <div class="card h-100">
                        <div class="card">
                            {% if t.picture %}
                            <a href="{% url 'quotation:single' t.slug %}">
                                <img src="{{t.picture.url}}" class="card-img-top" alt="...">
                            </a>
                            {% endif %}
                            <div class="card-body">
                                <h5 class="card-title">{{t.title}}</h5>
                                <p class="card-text"><i class="fa fa-map-marker"></i>{{t.org_name}}</p>
                                <p class="card-text"><i class="fa fa-briefcase" aria-hidden="true"></i>{{t.service}}</p>
                           <p class="card-text"><i class="fa fa-newspaper-o" aria-hidden="true"></i>{{t.published_on}}</p>
                            </div>
                            <ul class="list-group list-group-flush">
                                <li class="list-group-item">Published Date: {{t.published_date|date}}</li>
                                <li class="list-group-item">Last Date: {{t.last_date|date}}</li>
                            </ul>
                            <a href="{% url 'quotation:single' t.slug %}" class="btn btn-primary">Visit Tender/Notice</a>
                        </div>
                    </div>
                </div>
                {% endfor %}

            </div>

</section>

tenderwebsite-main/tenderwebsite-main/tender/tenderapp/templates/tenderapp/snippets/sidebar.html
<ul class="list-group"  id="sidebar">
            <a href="{% url 'tenderonly:all' %}">
                <li class="list-group-item">Tender - बोलपत्र</li>
            </a>
            <a href="{% url 'quotation:all' %}">
                <li class="list-group-item">Quotation - दरभाउपत्र</li>
            </a>
            <a href="{% url 'auction:all' %}">
                <li class="list-group-item">Auction - लिलामी</li>
            </a>
            <a href="{% url 'proposal:all' %}">
                <li class="list-group-item">Proposal - प्रस्तावना</li>
            </a>
            <a href="{% url 'eoi:all' %}">
                <li class="list-group-item">EOI - आशयपत्र माग</li>
            </a>
            <a href="{% url 'standinglist:all' %}">
                <li class="list-group-item">Standing List - सूचीदर्ता</li>
            </a>
            <a href="{% url 'intent2awards:all' %}">
                <li class="list-group-item">Intent to Award - आशयपत्र जारी</li>
            </a>
        </ul>

tenderwebsite-main/tenderwebsite-main/tender/tenderapp/templates/tenderapp/snippets/tender.html
<section id="tender">
    <div class="alert alert-success" role="alert">
        <h2> <a href="{% url 'tenderonly:all' %}">Tender - बोलपत्र</a> </h2>
    </div>
<br>
    <div class="card-group">
                {% for t in tender %}
                <div class="col-sm-6 col-md-6 col-lg-3 col-xl-3">
                    <div class="card h-100">
                        <div class="card">
                            {% if t.picture %}
                            <a href="{% url 'tender:single' t.slug %}">
                                <img src="{{t.picture.url}}" class="card-img-top" alt="...">
                            </a>
                            {% endif %}
                            <div class="card-body">
                                <h5 class="card-title">{{t.title}}</h5>
                                <p class="card-text">{{t.org_name}}</p>
                                <p class="card-text"><i class="fa fa-briefcase" aria-hidden="true"></i>{{t.service}}</p>
                            <p class="card-text"><i class="fa fa-newspaper-o" aria-hidden="true"></i>{{t.published_on}}</p>
                            </div>
                            <ul class="list-group list-group-flush">
                                <li class="list-group-item">Published Date: {{t.published_date|date}}</li>
                                <li class="list-group-item">Last Date: {{t.last_date|date}}</li>
                            </ul>
                            <a href="{% url 'tender:single' t.slug %}" class="btn btn-primary card-footer">Visit Tender/Notice</a>
                        </div>
                    </div>
                </div>
                {% endfor %}

            </div>


</section>