tenderwebsite-main/tenderwebsite-main/tender/eoi/urls.py
from django.urls import path
from . import views

app_name = 'eoi'


urlpatterns = [
    path('', views.all, name='all'),
    path('<slug>', views.single, name='single'),
]

tenderwebsite-main/tenderwebsite-main/tender/standinglist/urls.py
from django.urls import path
from . import views

app_name = 'standinglist'


urlpatterns = [
    path('', views.all, name='all'),
    path('<slug>', views.single, name='single'),
]

tenderwebsite-main/tenderwebsite-main/tender/tender/urls.py
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('accounts.urls')),
    path('logout/', views.user_logout, name='logout'),

    path('', include('tenderapp.urls')),
    path('tender/', include('tenderonly.urls')),
    path('auction/', include('auction.urls')),
    path('eoi/', include('eoi.urls')),
    path('intent2award/', include('intent2awards.urls')),
    path('others/', include('others.urls')),
    path('proposal/', include('proposal.urls')),
    path('quotation/', include('quotation.urls')),
    path('standing-list/', include('standinglist.urls')),
    path('advertising/', include('advertise.urls'), name='advertising'),

    path('s/', views.search, name='search'),
    path('u/', include('profiles.urls', namespace='profiles')),

    path('aboutus/', views.AboutUs.as_view(), name='aboutus'),
    path('contact-us/', views.ContactUs.as_view(), name='contactus'),
    path('pricing/', views.Pricing.as_view(), name='pricing'),
    path('faq/', views.Faq.as_view(), name='faq'),
    path('team/', views.Team.as_view(), name='team'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

tenderwebsite-main/tenderwebsite-main/tender/standinglist/models.py
from django.db import models
from django.urls import reverse


def upload_location(instance, filename):
    return "%s/%s" % (instance.title, filename)


def document_upload_location(instance, filename):
    return "%s/%s"%(instance.syllabus, filename)


class StandingList(models.Model):
    title = models.CharField(max_length=255, unique=True)
    org_name = models.CharField(max_length=50, blank=True, null=True)
    org_address = models.CharField(max_length=50, blank=True, null=True)
    service = models.CharField(max_length=50, blank=True, null=True)
    tender_description = models.TextField()
    syllabus = models.FileField(upload_to=document_upload_location, blank=True, null=True)
    published_on = models.CharField(max_length=55, unique=True)
    published_date = models.DateTimeField()
    last_date = models.DateTimeField()
    picture = models.ImageField(upload_to=upload_location, blank=True, null=True)
    slug = models.SlugField(allow_unicode=True, unique=True, blank=True, null=True)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("standinglist:all", kwargs={'slug': self.slug})

tenderwebsite-main/tenderwebsite-main/tender/standinglist/views.py
from django.http import Http404
from django.shortcuts import render
from .models import StandingList
from memberships.models import Membership, UserMembership


def all(request):
    auction = StandingList.objects.order_by('-published_date')
    context = {'auction': auction}
    template = 'standinglist/all.html'
    return render(request, template, context)


def single(request, slug):
    try:
        auction = StandingList.objects.get(slug=slug)
        user_membership = UserMembership.objects.filter(user=request.user).first()
        user_membership_type = user_membership.membership.membership_type

        context = {'tender': auction, 'user_membership_type':user_membership_type}
        template = 'standinglist/single.html'
        return render(request, template, context)

    except:
        return render(request, 'loginrequired.html')

tenderwebsite-main/tenderwebsite-main/tender/standinglist/templates/standinglist/all.html
{% extends 'base.html' %}
{% block content %}

  {% if user.is_authenticated%}

{% include 'tenderapp/snippets/horizontal-sidebar.html' %}
<br>
<div class="card-group">
                {% for t in auction %}
                <div class="col-sm-12 col-lg-3">
                    <div class="card h-100">
                        <div class="card">
                            {% if t.picture %}
                            <a href="{% url 'standinglist:single' t.slug %}">
                                <img src="{{t.picture.url}}" class="card-img-top" alt="...">
                            </a>
                            {% endif %}
                            <div class="card-body">
                                <h5 class="card-title">{{t.title}}</h5>
                                <p class="card-text">{{t.org_name}}</p>
                                <p class="card-text"><i class="fa fa-briefcase" aria-hidden="true"></i>{{t.service}}</p>
                            <p class="card-text"><i class="fa fa-newspaper-o" aria-hidden="true"></i>{{t.published_on}}</p>
                            </div>
                            <ul class="list-group list-group-flush">
                                <li class="list-group-item">Published Date: {{t.published_date|date}}</li>
                                <li class="list-group-item">Last Date: {{t.last_date|date}}</li>
                            </ul>
                            <a href="{% url 'standinglist:single' t.slug %}" class="btn btn-primary card-footer">Visit Tender/Notice</a>
                        </div>
                    </div>
                </div>
                {% endfor %}

            </div>

 {% else %}
    <div class="alert alert-success" role="alert">
        <h3 class="alert-heading">Login Required!</h3>
        <p>Please signup to view this document. to register, click the login button from the above and click the option register here.</p>

        <hr>
        <p class="mb-0">See you soon!</p>
    </div>
    {% endif %}
    <br><br><br><br><br><br><br>
{% include 'singlead/singlebottom.html' %}

{% endblock %}

tenderwebsite-main/tenderwebsite-main/tender/standinglist/templates/standinglist/single.html
{% extends 'base.html' %}

{% block content %}
<section id="single">
    {% if user.is_authenticated%}
    {% if not user_membership_type == 'Off' %}

    <div class="row">
        <div class="col-md-9">

    <div class="container-fluid single">
        <h1>{{tender.title}}</h1>
        <h2>{{tender.org_name}}</h2>
        <div class="row">
            {% if tender.published_date %}
            <div class="col-md-3">
                <i class="fas fa-calendar"></i><span>{{tender.published_date}}</span></i>
            </div>
            {% endif %}
            {% if tender.last_date %}
            <div class="col-md-3">
                <i class="fas fa-calendar"></i><span>{{tender.last_date}}</span></i>
            </div>
            {% endif %}
            {% if tender.org_address %}
        <div class="col-md-3">
                <i class="fas fa-map-marker-alt"></i><span>{{tender.org_address}}</span></i>
            </div>
            {% endif %}
        </div>
        {% if tender.picture.url %}
            <img src="{{ tender.picture.url }}" width="100%" height="600px">
        {% endif %}
        <div class="jumbotron">
            <h5>{{tender.tender_description}}</h5>
            <h3>{{tender.service}}</h3>
            <h5>{{tender.tender_description}}</h5>
            <h4>{{tender.published_on}}</h4>
        </div>
    </div>
        </div>



        <div class="col-md-3">
            <br>{% if tender.syllabus%}
                <div class="col-md-10">
                    <marquee behavior="scroll" direction="left" scrollamount="3"> Document View </marquee>
                </div>

                <div class="" align="center">
                    <object data="{{ tender.syllabus.url }}" type="application/pdf" width="400" height="500">
                        <embed src="{{ tender.syllabus.url }}" type="application/pdf">
                            <p>This browser does not support PDFs. Please download the PDF to view it: <a href="{{ course.syllabus.url }}">Download PDF</a>.</p>
                        </embed>
                    </object>
                </div>
            {% endif %}
        </div>
    </div>
{% else %}
        {% include 'renew.html' %}
        {% endif %}
     {% else %}
    <div class="alert alert-success" role="alert">
        <h4 class="alert-heading">Login Required!</h4>
        <p>Please signup to view this document. to register, click the login button from the above and click the option register here.</p>
        <hr>
        <p class="mb-0">See you soon!</p>
    </div>
    {% endif %}
</section>
{% endblock %}